### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by rcoup** [jkehler/awslambda-psycopg2#1]
Would be great to have a version with SSL support. The OpenSSL libs are included on the Amazon AMI already. AFAICT something like this seems to work:
* `yum install openssl-devel` (OpenSSL headers)
* (for postgresql) `/configure --prefix=$(pwd) --without-readline --without-zlib --with-openssl`
* (for psycopg2) add `libraries=ssl crypto` to `setup.cfg`

Then maybe also bundle the Redshift CA certificate (http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html#connect-using-ssl) to the `psycopg2/` directory?

Then can use via:
```
db = psycopg2.connect(
    ...,
    sslmode='verify-ca',
    sslrootcert=os.path.join(os.path.dirname(os.path.realpath(__file__)), 'psycopg2/redshift-ssl-ca-cert.pem')
)

**Comment by torstenrudolf** [comment]
that worked just beautiful! thanks dude

**Comment by skiller3** [comment]
I need SSL from lambda as well.  I'll try to submit a pull request based on rcoup's comment.

**Comment by torstenrudolf** [comment]
i added a pull request #4

**Comment by jkehler** [comment]
@torstenrudolf PR has been merged and SSL is now supported.
