### ISSUE TITLE
No module named psycopg2

### ISSUE THREAD

**Issue by aws-redshift** [jkehler/awslambda-psycopg2#11]
I am facing the same issue what other people have faced. 
Extracted and Copied psycopg2 in windows into my AWS Lambda zip package along-with my python file and site packages.
As suggested in #3 , changed the permission, transferred file back to windows and zipped again into my AWS Lambda package.
Below is my code snippet 

`#!/usr/bin/python
import psycopg2
import sys
import pprint
import datetime

def lambda_handler(event, context):

#Connect to RedShift
conn_string = "dbname='XXXX' port='5439' user='XXX' password='XXXX' host='XXXXXXXXXXXX'";

conn = psycopg2.connect(conn_string);
cursor = conn.cursor();

cursor.execute("begin transaction");
cursor.execute("truncate table XXXX");
cursor.execute("truncate table XXXX");
cursor.execute("truncate table XXXX");
cursor.execute("delete from XXXX");
cursor.execute("insert into XXXX");
cursor.execute("truncate table XXXX");
cursor.execute("truncate table XXXX");
cursor.execute("truncate table XXXX");
cursor.execute("end transaction");

conn.commit();
conn.close();`

My zip structure
`.
+-- python_script.py
+-- psycopg2
    +-- psycopg2 files`

Is it something that I am doing wrong, did I miss anything?

**Comment by NicklasOstman** [comment]
I had the same problem, changing permissions and using the package in this rep with no results.

I then stumbled on this [blog](http://www.iheavy.com/2016/02/14/getting-errors-building-amazon-lambda-python-functions-help-howto/) and moved the psycopg2 package (from this rep) to root proj directory before zipping the deployment package.

This did the trick for me.

**Comment by aws-redshift** [comment]
Oh great! Unfortunately, I moved to node.js since I could not find the solution on time. @jkehler - probably you should add this step - Move psycopg2 package to root proj directory before zipping.
