### ISSUE TITLE
No luck getting psycopg2 to work on AWS Lambda.

### ISSUE THREAD

**Issue by crowdwave** [jkehler/awslambda-psycopg2#16]
Hey there

I've given this a shot but nothing I do will get psycopg2 to run on my Lambda.  It never gets past trying to establish the connection and I can’t even get any sort of error message - just complete silence from that point in my code.  Ugh.

Would you be willing to upload to github a zipfile of a an AWS Lambda function that you know works and uses psycopg2?  Then I could examine it and see what you are doing to make it work.

thanks heaps!

**Comment by phouse512** [comment]
hey @crowdwave, I've been working with Lambda recently and used this package to help me get psycopg on my functions.  

I took one of my zipped uploads and stripped out my handler code and re-zipped it up and put it on my google drive, you can find the file here: [sample_lambda_zip](https://drive.google.com/file/d/0B_cauGqExC3ebDlHYUQwWmdzVUU/view)

Hopefully you can modify that handler and see if you can get your code to work. The other thing that I would watch out for is making sure that your Lambda function has network access to your DB. 

For example, I host my postgres database using RDS, and I had to add my Lambda function to the RDS vpc and make sure that the routing rules supported incoming requests to it.  By default, lambda functions usually get placed in their own VPC, so definitely double check that.  I had some troubles there as well when I initially was getting this up and running.

**Comment by crowdwave** [comment]
@phouse you are a life saver than you so much - I spent a ridiculous amoutn of time trying to fix the wrong problem - it was the vpc configuration of the lambda function all along. 

Thanks massively for your help - once I had known good code I was forced to think of what else it could be.

**Comment by phouse512** [comment]
@crowdwave glad it worked out 👍
