### ISSUE TITLE
compile/setup against python 3.6.1 ?

### ISSUE THREAD

**Issue by jjmartin** [jkehler/awslambda-psycopg2#17]
now that Lambda supports python 3.6 https://aws.amazon.com/about-aws/whats-new/2017/04/aws-lambda-supports-python-3-6/

is there a chance you could make a 2nd package that we could use in our 3.6 lambdas? 

Thanks

**Comment by cbefus** [comment]
bump.  I tried doing this myself today and failed miserably.

**Comment by jkehler** [comment]
I've just merged in a PR that adds 3.6 support. Thanks @dropthemic for the PR.
