### ISSUE TITLE
Throwing and error on AWS Lambda

### ISSUE THREAD

**Issue by kirill-andr** [jkehler/awslambda-psycopg2#19]
Hi,
Like many other users I am experiencing issue with Postgres connectivity on Lambda. I have downloaded your psycopg2-3.6 directory and copied it in the root directory of my function. I also did a CHMOD 777 on the directory as it seems that some users reported that to have solved the issue. But I still get the error 
Unable to import module 'rds-to-stream': No module named 'psycopg2' on Lambda. also, when I run it locally now I get the error
ImportError: No module named 'psycopg2._psycopg'

**Comment by Athulus** [comment]
did you rename the directory to psycopg2?
