### ISSUE TITLE
No module named 'psycopg2._psycopg'

### ISSUE THREAD

**Issue by shivekkhurana** [jkehler/awslambda-psycopg2#23]
Hi @jkehler, community,

Thanks for creating and maintaining this life saver package !

I'm working with python3.6 and have copied the pyscopg2-3.6 folder to my root and renamed it to pscopg2. But even after doing so, the app was not able to import psycopg (this was the error : `Driver "postgres" requires "psycopg2" package`)

I fired a terminal and tried to import `psycopg2` manually, but it failed with the following error : 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ModuleNotFoundError: No module named 'psycopg2._psycopg'
```

Here are the contents of my `psycopg2` folder : 
![screen shot 2017-09-07 at 9 53 02 pm](https://user-images.githubusercontent.com/1925158/30173951-02827256-9417-11e7-9f95-6850683b6a80.png)

What am I doing wrong here ? 
How should I go about it ?

Thanks

------
PS : I'm on macOS running python3.6.

**Comment by shivekkhurana** [comment]
Maybe, this is similar to #19. But that issue is closed without a solution.

**Comment by sar009** [comment]
I am having the same issue.

**Comment by jkehler** [comment]
Are you guys happening to use this library on your local development machines that is not Linux? Eg on your Mac. If this is the case then this library will not work as it's compiled for Linux which is what the Lambda environment is.

**Comment by shivekkhurana** [comment]
Yes. I'm using it on a Mac. Will this work when deployed on lambda?

**Comment by jkehler** [comment]
@shivekkhurana yes it should. You can't run Linux compiled binaries on your Mac system. Hence the import error.

**Comment by sar009** [comment]
i am having issues on a linux machine too

**Comment by jkehler** [comment]
@sar009 please test it on Lambda. This library is only guaranteed to work on the Amazon Lambda AMI machines. For local development you should just be using the usual libraries supplied by pip.

**Comment by sar009** [comment]
yes it is working fine on lambda. now there is another problem it is not connecting.

**Comment by jkehler** [comment]
@sar009 Lambda functions by default do not have outside access to the Internet. If your database is hosted within AWS then you'll have to make sure to have your lambda function in the same VPC. If it's not in AWS then you'll have to do all kinds of funky workarounds to get outside access to the internet.

**Comment by jkehler** [comment]
@shivekkhurana i'm going to assume you were having the same issue has @sar009 I'm closing this ticket now.

**Comment by brentonmallen1** [comment]
@jkehler I just came across this same issue on lambda. `No module named 'psycopg2._psycopg'` Are there any suggested debugging things I can look into?

The lambda runtime i'm using is python3.6 and just copied over the 3.6 directory over and renamed it as suggested.
