### ISSUE TITLE
Error: "no pg_hba.conf entry for host"

### ISSUE THREAD

**Issue by 2wheeladdict** [jkehler/awslambda-psycopg2#25]
Thanks for putting this together.  So, I'm having a bit of problem getting the connection finalized.  I have cloned the repo and copied the **psycopg2** directory into the Lambda deployment package per the instructions.  When I attempt to connect using host, database, user and password values (which I have verified from another machine are valid), the following error is thrown:

`no pg_hba.conf entry for host`

I've also attempted to use the **with_ssl_support/psycopg2** files and received the following error:

```
FATAL: no pg_hba.conf entry for host "12.34.56.789", user "my_user", database "foobar", SSL off
: OperationalError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 47, in lambda_handler
conn = psycopg2.connect(host="foobar.com", database="foobar", user="my_user", password="secret")
File "/var/task/psycopg2/__init__.py", line 130, in connect
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
OperationalError: FATAL: no pg_hba.conf entry for host "12.34.56.789", user "my_user", database "foobar", SSL off
```

**Comment by jkehler** [comment]
This is a problem on your database end. Your database is currently setup to only allow connections from certain IP addresses and it is currently blocking connections from the Amazon IP. You have to edit the pg_hba.conf file on your PostgreSQL server to allow the connections.
