### ISSUE TITLE
Unable to import module using Python 3.6

### ISSUE THREAD

**Issue by fcusano9** [jkehler/awslambda-psycopg2#28]
Hi, I am using Python 3.6 with pyscopg2 and I am trying to run this code on a lambda function. I tried adding both of the folders in this repo to my zip file but neither worked, I keep getting this error:

`Unable to import module 'lambda_function': /var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8`

Is there something I am doing wrong? Any help would be appreciated, thank you in advance.

**Comment by jkehler** [comment]
@fcusano9 you need to use the psycopg2-3.6 folder. Copy this folder to your lambda project and then rename it to just psycopg2
