### ISSUE TITLE
Undefined symbol: PyUnicodeUCS4_DecodeUTF8

### ISSUE THREAD

**Issue by FlavioCestari** [jkehler/awslambda-psycopg2#29]
Hey @jkehler 

I’m getting the error below when I try to run on AWS Lambda:

`Unable to import module 'handler': /var/task/psycopg2/_psycopg.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8`

**Comment by atsuky** [comment]
@FlavioCestari Are you running it on Python3.6 ? If it's the case you need to you use the psycopg2-3.6 folder. Copy this folder to your lambda project and then rename it to just psycopg2

That should work

**Comment by FlavioCestari** [comment]
Ok, many thanks. ;)
