### ISSUE TITLE
No module named psycopg2, import psycopg2 doesn't work on lambda

### ISSUE THREAD

**Issue by ToMMy86** [jkehler/awslambda-psycopg2#3]
Hello,
i called my .py script :  "lambda_function.py"    ( the handler in the config tab of lambda console is : lambda_function.lambda_handler   so i guess it's ok )  ... my zip structure of the package to upload is the same as shown by kylebuckingham in another issue closed... 
i have : 1 file + psycopg2 lib ...  the goal of my simple script is to trigger a scheduled vaacuum on a pgsql table

my zip structure in detail :

```
.
+-- lambda_function.py
+-- psycopg2
    +-- psycopg2 files
```

 here is a snippet of my code [lambda_function.py]: 
```python
from __future__ import print_function
from datetime import datetime
import os
import psycopg2

con = None
query = ''

def lambda_handler(event, context):
    print('Scheduled maintenance started at {}'.format(str(datetime.now())))
    try:
        host = "THE DB HOST"
        database = "DB NAME"
        user = "DBUSER"
        password = "DBPASS"
        days = "7"
        
        con = psycopg2.connect(host=host, database=database, user=user, password=password) 
        cur = con.cursor()
        cur.execute('SELECT ..... ' + 
                    'FROM pg_stat_all_tables ' +
                    "WHERE schemaname = 'foo' " +
                    "AND relname = 'bar' " +
                    'AND ((last_analyze is NULL ' +
                    'AND last_autoanalyze is NULL)' +
                    'OR ((last_analyze < last_autoanalyze OR last_analyze is null) ' +
                    "AND last_autoanalyze < now() - interval %s) " +
                    'OR ((last_autoanalyze < last_analyze OR last_autoanalyze is null) ' +
                    "AND last_analyze < now() - interval %s));", [days + ' day', days + ' day'])
        rows = cur.fetchall()
        con.set_isolation_level(0)
        for row in rows:
            query = 'VACUUM ANALYZE %s;' % (row[0])
            cur.execute(query)

    except psycopg2.DatabaseError, e:
        print('Error: %s' % e)
        raise
    else:
        print('Vaacuum done!')
        return event['time']
    finally:
        print('Scheduled maintenance completed at {}'.format(str(datetime.now())))
        if con:
            con.close()
```

The error when testing in lambda:   "Unable to import module 'lambda_function': No module named psycopg2"

Any clue on why is not working for me ? Is this the correct way to import the module ?  Thank you very much !

**Comment by maikfl** [comment]
if you don't mind check your uploaded and saved code (actions -> download function code) and check the folder structure and if everything is there (zip -r)

i created a testcase with the current release and it's working fine

**Comment by ToMMy86** [comment]
Thanks for the quick answer .. done but looks everything is in place and exaclty as shown in the previous message... che code of my function is the same ( with the correct values )  and the structure is the same.. the zip content downloaded from lambda is  correct 

```
.
+-- lambda_function.py
+-- psycopg2
    +-- psycopg2 files
```
Maybe the only difference is that i'm using lambda in the EU ireland region ... can be a bug of lambda iteself on ireland region ? I was unable to find more documentation .. would you please be so kind to attach me somewere your zip example ?  Thanks for the support.

**Comment by jkehler** [comment]
I have no idea why your import would not be working. If possible would you be attach your zip package (with all sensitive information removed of course) for further examination?

Also @kylebuckingham had this issue a few weeks ago but he said he figured it out and closed the issue without providing any context as to what fixed it.

**Comment by ToMMy86** [comment]
Here you are, inside you will find  : 
What i'm uploading to Lambda = lambda_function.zip
The content of the downloaded package FROM lambda ( after my upload ) = testVaacuum-*.zip
Some screenshots of the error as shown in lambda and the configuration tab 


```
https://www.zipshare.com/download/eyJhcmNoaXZlSWQiOiI2OTNmNjQ5Yi02NGNjLTQ2YzEtYjIzNS1jMWM5ZWY1ODY5ODcifQ==
```
Thank you !

**Comment by jkehler** [comment]
It's got to be something with how your creating your zip package. I tried your zip package in lambda and did experience the same import error. I then extracted your zip package and recreated it myself and uploaded to lambda and the import is working fine.

I noticed your zip package is 387KB while mine is 407KB created from the exact same files.

**Comment by ToMMy86** [comment]
Arg ! .. ok then i'll try with another machine and let you know the result !

Thanks for the support again !

**Comment by maikfl** [comment]
i got your zip running
drwxrwxr-x for psycopg2 folder. i don't know the exact permissions, but with the rights from zip it wasn't possible. after changes and upload it worked.

**Comment by ToMMy86** [comment]
Ok now it's working  .. @maikfl  is right  it was a permission problem .. here is what i've done so far : 
I'm using Fedora 23 workstation with Gnome 3 

Downloaded the .zip  of this project from githup ... extracted with gnome on the root dir of my package
The default permission seems to be :  700  ( due probably to default umask )  

I was doing the .zip also with the gnome interface simply ... so i've changed the permission before making the zip of my package 

```
chmod -R 775 psycopg2 
```
And AFTER that i made the .zip ... seems like lambda env is bothering about source permissions...so  is mandatory to fix them out before packaging if using linux ...( I thought lambda would have set permissions automatically during extraction in its environment .. but evidently is not so) 

NOW IS WORKING OK :D 

Hope this is going to help someone else with the same issue out there... thank you all for your time !
Tommaso

**Comment by rabinnh** [comment]
I had the same issue.  Didn't even think of looking at the permissions of the unzipped folder.  Thanks.

**Comment by CBeri9496** [comment]
Hello,

I am also facing same error but I am working on windows 10. I am new to using Lambda functions. Can you please help me to set permissions using powershell.

Thanks,
Chandana

**Comment by jkehler** [comment]
@CBeri9496 Please take a look at #23. You won't be able to use this package on a Windows 10 machine. This package will only work in the final zip file you upload to AWS Lambda. For local development please use the psycopg2 library that pip provides.

**Comment by CBeri9496** [comment]
Thanks for your response. Actually I have been using psycopg2 library which is provided by pip. I have changed permissions as chmod -R 775 using gitbash, still getting same error. I am not sure where I am doing mistake.
![error](https://user-images.githubusercontent.com/16859646/30827479-da3add14-a1ff-11e7-9711-c70d4e7aa61a.PNG)

**Comment by gnulnx** [comment]
Same error here.  It's definitely just source file permissions in all cases.  For me all other packages are correctly built and uploaded.  psycopg2 is done the exact same way.  But it fails ONLY on import of psycopg2.  :/

**Comment by thimmareddykv** [comment]
@ToMMy86  Can you share your code snippet.

I am trying to the same connecting to PGS using lambda function.

I am not sure on how to do this,

+-- lambda_function.py
+-- psycopg2
    +-- psycopg2 files

**Comment by ToMMy86** [comment]
> @ToMMy86 Can you share your code snippet.
> 
> I am trying to the same connecting to PGS using lambda function.
> 
> I am not sure on how to do this,
> 
> +-- lambda_function.py
> +-- psycopg2
> +-- psycopg2 files

Hello, 

Here is an example of my code ( Vacuum analyze on some tables ) using psycopg2. 
Read the earlier messages about the permission of the psycopg2 folder before making the zip package.

Hope this helps 

[lambda-psycopg2-example.zip](https://github.com/jkehler/awslambda-psycopg2/files/2374631/lambda-psycopg2-example.zip)

**Comment by tomisaacson** [comment]
I had the same problem until I changed my lambda to use Python 3.6. It doesn't work if you use 3.7!

**Comment by rpathak3** [comment]
Facing the same issue, getting an error "Unable to import module 'main': No module named 'psycopg2._psycopg'" when using the pyscopg2-3.7 module (with ssl support). Works fine with the psycopg2-3.6 module (with ssl support).
