### ISSUE TITLE
psycopg2 directory permissions are wrong

### ISSUE THREAD

**Issue by evanjoy** [jkehler/awslambda-psycopg2#30]
If I just copy & bundle up the existing psycopg2 directory, then I get errors trying to import it in my Lambda function.

Turns out the permissions on the psycopg2 directory were `rwx------` by default.

Fixed by `chmod 775 psycopg2`

Feedback: It'd be ideal if it either came down with the right permissions, or if the README.md file documented this issue so that new users don't have to experience and debug this issue every.

I'm on Ubuntu 16.04, if it matters.

**Comment by jkehler** [comment]
Not sure if this is really a problem. I just did a fresh clone of the repo onto my Linux machine and the files already had 0644 read permission for all users in the psycopg2 folder.
