### ISSUE TITLE
Build with ssl error

### ISSUE THREAD

**Issue by zhenyiy** [jkehler/awslambda-psycopg2#34]
./psycopg/psycopg.h:31:10: fatal error: libpq-fe.h: No such file or directory

**Comment by zhenyiy** [comment]
I am working on AWS Linux 1. Is it because package ssl and crypto do not exist

**Comment by kittipatkampa** [comment]
I got a similar error when running

`./configure --prefix /home/hadoop/psycopg2/postgresql-9.4.3 --without-readline --without-zlib --with-openssl`

This is the error message:
```
...
checking for library containing shmget... none required
checking for CRYPTO_new_ex_data in -lcrypto... no
configure: error: library 'crypto' is required for OpenSSL
```

**Comment by rpathak3** [comment]
> I got a similar error when running
> 
> `./configure --prefix /home/hadoop/psycopg2/postgresql-9.4.3 --without-readline --without-zlib --with-openssl`
> 
> This is the error message:
> 
> ```
> ...
> checking for library containing shmget... none required
> checking for CRYPTO_new_ex_data in -lcrypto... no
> configure: error: library 'crypto' is required for OpenSSL
> ```

Facing the same issue when trying to create the psycopg2 mode with ssl support.

**Comment by jkehler** [comment]
This just means your distribution doesn't have the required libraries installed needed to compile the package.
