### ISSUE TITLE
_psycopg.so: undefined symbol: _Py_ZeroStruct

### ISSUE THREAD

**Issue by Tonkonozhenko** [jkehler/awslambda-psycopg2#37]
Hi @jkehler 

I get a next error when I'm trying to use the library:

```
START RequestId: b7d75edc-9af5-11e8-a42b-719aa1d42326 Version: 6
Unable to import module 'index': /var/task/psycopg2/_psycopg.so: undefined symbol: _Py_ZeroStruct

END RequestId: b7d75edc-9af5-11e8-a42b-719aa1d42326
REPORT RequestId: b7d75edc-9af5-11e8-a42b-719aa1d42326	Duration: 1.15 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 34 MB
```

I also tried to compile lib with postgres 10.4 and latest psycopg2 and get the same error.

**Comment by Tonkonozhenko** [comment]
Forgot to mention, I used python 3.6.

**Comment by jkehler** [comment]
Did you use the psycopg2-3.6 directory in the repo and rename it to just psycopg?

**Comment by Tonkonozhenko** [comment]
Yes.

**Comment by jkehler** [comment]
Hmm not sure then. I'm away from my PC but I'll test it in a new lambda function later to see if I can replicate

**Comment by Tonkonozhenko** [comment]
Thanks, Jeff, I hope you will be able to replicate and fix it.

**Comment by Tonkonozhenko** [comment]
I don't know what happened, but it started working. Probably there were issues with copying files to lambda bundle. So now I delete all psycopg2* from bundle and only after that copy your files to bundle. Thanks!
