### ISSUE TITLE
awesome but still needed?

### ISSUE THREAD

**Issue by davehowell** [jkehler/awslambda-psycopg2#39]
I see the awslabs repo has an example lambda function that import psycopg2 and there's no fancy make files or things to suggest they are bundling the C library, maybe it's finally supported ?

See:
https://github.com/awslabs/rds-support-tools/blob/master/serverless/serverless-query.py.postgresql

**Comment by rae89** [comment]
@davehowell Any idea how they got this to work?  It still doesn't seem to be a native python package in lambda.

**Comment by davehowell** [comment]
Theres a file update-lambda.cli that refers to a zip file on S3, which I suspect has everything installed to it. 

In my case, using a mac, I've ended up using this precompiled package inside my lambda directory, and in another directory (../macpsychopg2) i have pip-installed the mac version. In the python script for the lambda handler I am committing a horrendous hack, checking what the host argument is and importing from the mac directory if it is "Darwin". When I deploy the lambda it packages the one from this repo.  I'm using terraform so this module is very helpful for lambda: https://github.com/claranet/terraform-aws-lambda

**Comment by rae89** [comment]
I have been using apex to deploy my lambda with this module manually moved to the directory apex deploys.  I was trying to download this repo by using requirements.txt and then building the lambda using the requirements, but no luck yet.

**Comment by LereveLabs** [comment]
@davehowell followed your hack and it's working for me.  If you find a better way let me know.  Thanks!

**Comment by rae89** [comment]
@davehowell I am curious to know how you are pulling this repo during the lambda packaging with terraform.

**Comment by davehowell** [comment]
@rae89 This particular repo? I am not pulling it during packaging, I originally just cloned it and copy-pasted the dir inside my lambda directory. The terraform module I am using zips it up into the deployment package. 

Since then we've switched to using docker with the aws lambci image, and building psycopg2 directly using instructions as per the readme on this site

**Comment by davehowell** [comment]
@LereveLabs I am using Pycharm and switched my project interpreter to be a docker image, using the lambci image with this package in it plus other dependencies installed. It means I can run tests locally on the mac using the same linux dependencies that get deployed in the zip package.
