### ISSUE TITLE
"errorMessage": "'psycopg2.extensions.connection' object has no attribute 'cusor'

### ISSUE THREAD

**Issue by GNNotionlabs** [jkehler/awslambda-psycopg2#43]
Hi all,
I have connected to AWS RDS Postgres with psycopg2-3.6 but can't use cusor or execute command.

Anyone resolve this issue?
_START RequestId: 1932d209-b708-4adb-8690-ce77059c867e Version: $LATEST
'psycopg2.extensions.connection' object has no attribute 'cusor': AttributeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 13, in lambda_handler
    cur = conn.cusor()
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'cusor'_

1. Python Runtime: 3.6
2. psycopg2-3.6

Here is my code very simple
`import sys
import logging
import psycopg2
import psycopg2.extras

def lambda_handler(event, context):
  conn=psycopg2.connect("dbname=*** host=*** port=5439 user=*** password=***")

  #Connect and execute scripts
  cur = conn.cusor()
  cur.execute("TRUNCATE TABLE dwh_ods.rpt12_bcbs_payroll_report;")
  conn.commit()
  conn.close()
  return "Executed!"`

**Comment by hero0926** [comment]
i think psydopg2 for python3 has some error

**Comment by GNNotionlabs** [comment]
I still can use it on Windows 10 or Ubuntu but when deploy to AWS Lambda, it's failed. So sad!

**Comment by Jflick58** [comment]
@GNNotionlabs  uh I think you meant to type 'cursor' not 'cursor'... probably the cause

**Comment by GNNotionlabs** [comment]
> @GNNotionlabs uh I think you meant to type 'cursor' not 'cursor'... probably the cause

Very thank you, it's working :D
