### ISSUE TITLE
Lambda now supports a Python v3.8 runtime

### ISSUE THREAD

**Issue by JamesCropcho** [jkehler/awslambda-psycopg2#53]
Hello,

Thanks for a great distribution!

So, AWS Lambda now supports a Python v3.8 runtime. I am writing "an FYI," to let you know out of gratitude for the project.

Pardon, this is not an "issue" per se, however I did not know of a better location to state the above.

―James

**Comment by tmm** [comment]
Pull request open for this https://github.com/jkehler/awslambda-psycopg2/pull/60

**Comment by jkehler** [comment]
PR #60 has been merged
