### ISSUE TITLE
Compilation at step python setup.py build fails for python3.7

### ISSUE THREAD

**Issue by Play9win** [jkehler/awslambda-psycopg2#56]
Hi there,

The compilation fails at the step where it involves 
`python3 setup.py build`
 
for python3.7. Is there any way to run it for python .

Here is the error:

![image](https://user-images.githubusercontent.com/54166943/77978334-7148d380-731f-11ea-84fb-7dcde0700ae6.png)

**Comment by jkehler** [comment]
Please check the latest 3.7 build that was just merged
