### ISSUE TITLE
Not an actual issue

### ISSUE THREAD

**Issue by dankram** [jkehler/awslambda-psycopg2#6]
I didn't have any other way of contacting you. I am having a similar problem with the lxml library and was wondering if you had any thoughts on how to compile that for aws lambda as well. Thanks for the psycopg2 that was a huge help as well.

**Comment by jkehler** [comment]
@dankram I'm not sure since I don't use the lxml library. I suspect a similar compilation of the C libraries with static linking is needed if it depends on system libraries that don't exist in Lambda.
