### ISSUE TITLE
ImportError: Error loading shared library libssl.so.10

### ISSUE THREAD

**Issue by hakarapet** [jkehler/awslambda-psycopg2#61]
Getting this error when the lib is loading 

```
 import psycopg2
   File "/.....path to lambda....../lambdas/psycopg2/__init__.py", line 50, in <module>
     from psycopg2._psycopg import (                     # noqa
 ImportError: Error loading shared library libssl.so.10: No such file or directory (needed by /.....path to lambda....../lambdas/psycopg2/_psycopg.cpython-37m-x86_64-linux-gnu.so)
```

just copied the `psycopg2-3.7` folder into lambda directory and renamed it to `psycopg2`
python version 3.7

**Comment by bigsee** [comment]
@hakarapet I had the same error. Also on python 3.7. Uninstalling and re-installing postgres worked for me.

`brew uninstall postgres`
`brew install postgres`

**Comment by hakarapet** [comment]
@bigsee thanks for the comment.
- The issue I had was occurring on my CI level before getting to aws. I'm using "terraform" to build, but before that, I run tests on CI, this is where I was having issues. The image that I was using was causing the issue.

- The 3.7 lib that is provided in this repo actually worked on aws! Currently using that.

Thanks
