### ISSUE TITLE
libssl.so.1.1 : cannot open shared object file: No such file or director

### ISSUE THREAD

**Issue by cptkirkh** [jkehler/awslambda-psycopg2#66]
This maybe my mistake somewhere but when I run through your steps on the build process it all works except when I run the lambda function on a DB that requires SSL I get this error.  Did I do something wrong?

`{
  "errorMessage": "Unable to import module 'postgres_lambda': libssl.so.1.1: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "stackTrace": []
}`

**Comment by ilirosmanaj** [comment]
@cptkirkh , did you find a solution to this one? Getting the same message even after using the psycopg2 version with ssl support over here

**Comment by lkinley** [comment]
You have to compile on Amazon Linux, not Ubuntu.  You have to match what the Lambda Python runtime is running on.
3.6, 3.7 are on Amazon Linux, 3.8, 3.9 are on Amazon Linux 2.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
