### ISSUE TITLE
Are they plans to support Python 3.9?

### ISSUE THREAD

**Issue by pxg** [jkehler/awslambda-psycopg2#67]
I'm keen to use Python 3.9 on lambda, as far as I can tell this library doesn't support it yet, are there plans to do this? I'd be happy to help with the development if someone can point me in the right direction.

(Apologies if this technically isn't considered an issue)

**Comment by aamirenvy** [comment]
Hi, Is it available for 3.9 now?

**Comment by buchs** [comment]
I would use a 3.9 version also, if it were available. I wish there was some build information here, because I might create a PR to build 3.9 if I understood the process. Since nothing in this repo's released files seems to have changed in 2 years, I am guessing it is mostly not alive.

**Comment by jackhamburger** [comment]
@buchs  and @aamirenvy  Did you every find a 3.9 solution?

**Comment by buchs** [comment]
No, I guess it would be build it myself. I did suggest to AWS that they take on this project.

**Comment by gwilson185** [comment]
I stopped using this project a while back because I now use SAM to build my lambda in a docker container. Then I just specify psycopg2 in my requirements.txt and the correct binary lib gets loaded.

**Comment by ianbinder** [comment]
I just committed a PR for this. Waiting on approval.
