### ISSUE TITLE
No module named _psycopg

### ISSUE THREAD

**Issue by RoboDonut** [jkehler/awslambda-psycopg2#7]
cant seem to get this worked out. I saw that it was opened and promptly closed... any thoughts ?

**Comment by jkehler** [comment]
I'm not sure as I've never seen this error. My hunch is that it is related to permissions. See #3  for more details.

**Comment by vinayemmadi** [comment]
I have the same error. I tried changing permission on pyscopg2 in the root folder. @RoboDonut how did you resolve this issue?
