### ISSUE TITLE
get_cluster_credentials not working  for 3.8 version

### ISSUE THREAD

**Issue by santest21** [jkehler/awslambda-psycopg2#73]
Hi,
I'm using get_cluster_credentials to generate temporary password, It is working fine with python 3.7 version but getting 
FATAL:  password authentication failed for user "IAM:defaultuser" error when I use python 3.8 or 3.9 version.
It is generating temporary password but it is not working.

please help me on this.

Thanks.

**Comment by jkehler** [comment]
This error is not related to this particular project. `get_cluseter_credentials` is coming from the `boto3` library so perhaps you can reach out to them.
